cache:
  paths:
    - node_modules/
    
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - route=$(pwd)
    - npm install
    - npx ng build --prod --aot --build-optimizer --output-path=dist
    - rsync -raz $route/dist root@cometa.amvara.de:/home/amvara/projects/dip-more/