cache:
  paths:
    - node_modules/
    
stages:
  - deploy

deploy:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: deploy
  script:
    - route=$(pwd)
    - sudo rm -rf ./node_modules
    - sudo npm install
    - sudo npm install -g @angular/cli
    - sudo ng build --prod --aot
    - sudo rsync -raz $route/dist root@cometa.amvara.de:/home/amvara/projects/dip-more/