cache:
  paths:
    - node_modules/
    
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - route=$(pwd)
    - npm install
    - npm run build
    - sudo cp -rf ./dist/* /home/amvara/projects/dip-more/