cache:
  paths:
    - node_modules/
    
stages:
  - deploy

deploy:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: deploy
  script:
    - route=$(pwd)
    - npm install
    - npx ng build --prod --aot --build-optimizer --output-path=dist
    - cp -rf ./dist/* /home/amvara/projects/dip-more/