tasks:
  - before: npm install
  - name: serve
    command: npx ng serve --aot
    openMode: split-right
  - name: build
    command: npx ng build -c production
    openMode: split-right
  

ports:
  - port: 4200
    onOpen: open-preview