tasks:
  - name: dependencies
    init: >
      npm install &&
      gp sync-done dependencies
  - name: serve
    init: gp sync-await dependencies
    command: npx ng serve --aot
    openMode: split-right
  - name: build
    init: gp sync-await dependencies
    command: npx ng build -c production
    openMode: split-right
  

ports:
  - port: 4200
    onOpen: open-preview