version: '2.0'
services:
  node:
    image: node:10.16.3-alpine
    container_name: "dip_docker"
    restart: always
    volumes:
      - ".:/opt/code/."
      - "./entrypoint.sh:/entrypoint.sh"
    ports:
      - 4200:4200
    entrypoint: "/entrypoint.sh"
