version: '2.0'
services:
  node:
    image: node:14-alpine
    container_name: "dip_docker"
    restart: always
    working_dir: /opt/code
    volumes:
      - ".:/opt/code/."
      - "./entrypoint.sh:/entrypoint.sh"
    ports:
      - 4200:4200
    entrypoint: "/entrypoint.sh"
